print("Enter size in KLOC: ")
size = float(input())
print()

nominal_productivity = 2.5
print("To calculate the effort, enter the following values:")
print("Precedentness of the project is:")
print("6.20 (Very low)")
print("4.96 (Low)")
print("3.72 (Average)")
print("2.48 (High)")
print("1.25 (Very High)")
print("0 (Extra High)")
pd = float(input())

print("Development flexibility of the project is:")
print("5.07 (Very low)")
print("4.05 (Low)")
print("3.04 (Average)")
print("2.03 (High)")
print("1.02 (Very High)")
print("0 (Extra High)")
df = float(input())

print("Architecture Risk and Resolution of the project is:")
print("7.07 (Very low)")
print("5.65 (Low)")
print("4.24 (Average)")
print("2.83 (High)")
print("1.41 (Very High)")
print("0 (Extra High)")
ar = float(input())

print("Team Cohesion of the project is:")
print("5.48 (Very low)")
print("4.38 (Low)")
print("3.29 (Average)")
print("2.19 (High)")
print("1.10 (Very High)")
print("0 (Extra High)")
tc = float(input())

print("Process Maturity of the project is:")
print("7.80 (Very low)")
print("6.24 (Low)")
print("4.68 (Average)")
print("3.12 (High)")
print("1.56 (Very High)")
print("0 (Extra High)")
pm = float(input())

scaling_factor = 0.91 + 0.01 * (pd + df + ar + tc + pm)
effort = nominal_productivity * (size ** scaling_factor)
print("Effort required is:")
print(effort, "person month")
